services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: riot
      POSTGRES_PASSWORD: riot
      POSTGRES_DB: lol_esports
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
